version: '27.1.1'
services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern_songs_app
      
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
